### ISSUE TITLE
Thresholds for different AD methods

### ISSUE THREAD

**Issue by Adversarian** [wanghangpsu/acgan-ada#2]
Hi. 
First I would like to thank you for you work on "Anomaly Detection of Adversarial Examples using Class-conditional Generative Adversarial Networks". You mentioned here that a grid search was conducted to obtain the thresholds for different detection methods (D-AD, All-AD and G-AD). I would like to know if you could share the exact values for these thresholds as I couldn't find them in the code.

**Comment by wanghangpsu** [comment]
Hello,

Thanks for being interested in out work. 

For each detection method, we first get the detection statistics, and then get the minimum and maximum value of those detection statistics. And the thresholds will be generated using the following code for example:

`thresholds = np.arange(min_value-step_size, max_value+2*step_size, step_size)`

The step_size can be set to a small value like 0.5 to make the ROC curve smooth. 

Also, I noticed later that there is package for ROC and AUC.

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html

You can also use the package instead.

I hope this helps and please cite our paper if you think it is useful.
